[DSD-2512] Updated charts_dir and charts_url values.
mosip/mosip-compliance-toolkit-ui pull request #279
Opened 2023-04-21 13:25 UTC by Mohanraj209

2023-04-21 15:11 UTC, syedsalman3753 requested changes

2023-04-21 15:11 UTC, syedsalman3753 commented on .github/workflows/release_chart.yml
>            charts_dir: .
charts_dir: helm is required

2023-04-21 15:11 UTC, syedsalman3753 commented on helm/install.sh
helm install command should install the chart from mosip-helm gh-pages

2023-04-26 12:48 UTC, Rakshitha650 approved these changes

2023-05-03 06:32 UTC, syedsalman3753 approved these changes

2023-05-03 10:35 UTC, ckm007 approved these changes

2023-05-03 10:35 UTC, merged